server:
  port: 13000
spring:
  application:
    name: user-server-api


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      version: 1.0
      is-test: true