server:
  port: 13000
spring:
#  messages:
#    basename: i18n/validations
#    encoding: UTF-8
  application:
    name: user-server-api
# --- redis 配置开始 -----
  redis:
    # txy/showme
    host: 10.0.2.33
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    password: dev123456 # Redis服务器连接密码（默认为空）
    timeout: 3000
    jedis:
      pool:
        max-active: 8 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 8  # 连接池中的最大空闲连接 默认 8
        min-idle: 0  # 连接池中的最小空闲连接 默认 0
  session:
    redis:
      namespace: spring-session
# redis 配置结束




#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8080/eureka/
#  instance:
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
#    metadata-map:
#      version: 1.0
#      is-test: true
