server:
  port: 11000
spring:
  application:
    name: auth-server

jwt:
  secret: 123456 # 登录校验的密钥
  pubKeyPath: /Users/zhouchao/github/springCloudBase/auth-server/tmp/rsa/rsarsa.pub # 公钥地址
  priKeyPath: /Users/zhouchao/github/springCloudBase/auth-server/tmp/rsa/rsa.pri # 私钥地址
  expire: 30 # 过期时间,单位分钟
  cookieName: AUTH_TOKEN_COOKIE