
server:
  port: 13100
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      version: 1.0
      is-test: true
spring:
  application:
    name: other-api
# 统一处理结果返回
responseBodyAdvice:
  is-open: true
  # com.springcloudbase.advice.ResponseAdvisor，多个包配置'com.springcloud.other.provider.controller,com.springcloud.other.provider.service.impl'
  basePackages:  "com.springcloud.other.provider.controller"
