spring:
  profiles: dev
server:
  port: 13101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
    registry-fetch-interval-seconds: 5
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
    metadata-map:
      version: 1.0
      is-test: true
ribbon:
  ServerListRefreshInterval: 5000

# 统一处理结果返回
responseBodyAdvice:
  is-open: true
  # com.springcloudbase.advice.ResponseAdvisor，多个包配置'com.springcloud.other.provider.controller,com.springcloud.other.provider.service.impl'
  basePackages:  "com.springcloud.other.provider.controller"

