

server:
  port: 5002

spring:
  profiles: single
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: https://www.baidu.com?s=
          predicates:
            - Path=/baidu/**


