server:
  port: 5000

spring:
  profiles: single
  application:
    name: gateway-server
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway