server:
  port: 5004
spring:
  profiles: eureka
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: lb://USER-SERVER-API  # 目的地址  lb表示loadBalance 负载均衡
          predicates:
            - Path=/user/**  #请求地址：http://localhost:5000/user/**
          filters:
            - StripPrefix=1
#        - id: order_route
#          uri: lb://OrderServer
#          predicates:
#            - Path=/order/**
#          filters:
#            - StripPrefix=1
#上面这段配置的意思是，配置了一个 id 为 user_route 的路由规则，
#当访问地址 http://localhost:5000/user/* 时会自动转发到地址：http://localhost:2101/*
#配置完成启动项目即可在浏览器访问进行测试，这里是没有 加入eureka注册中心的
logging:
  level:
    root: info
    org:
      springframework:
        cloud:
          gateway: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port}


