server:
  port: 5003

zuul:
  routes:
    xxx:
#      test1
#      这里请求的是  localhost:5003/forword1/  默认就会去请求到当前服务的 /hello请求
#      这里请求的是  localhost:5003/forword1/test  默认就会去请求到当前服务的 /hello/test 请求

#     如果是上面两种 forward:/hello   LimitFilter 中   setSendZuulResponse(false) 对 forward 是不起作用的，
#     需要设置 ctx.set("sendForwardFilter.ran"，true) 才行
      path: /forword1/**
      url: forward:/hello


#      这里表示所有的请求都会打到 http://localhost:5003/hello 上
#      path: /**
#      url: http://localhost:5003/hello