spring:
  profiles:
    active: ${spring.profiles.avtive:dev}
  application:
    name: eureka-server

---
server:
  port: ${port:8080}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/,http://localhost:8081/eureka/
spring:
  profiles: dev


---
server:
  port: ${port:8081}
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
spring:
  profiles: test