server:
  port: 14000
spring:
  application:
    name: fastdfs-server



#新的
fdfs:
  so-timeout: 1501
  connect-timeout: 601
  thumb-image:             #缩略图生成参数
    width: 150
    height: 150
  tracker-list:            #TrackerList参数,支持多个
#      - 192.168.1.113:22122
      - 192.168.1.114:22122
